name: Automated Vuetify Deploy

on:
  push:
    branches:
      - main  # This triggers the script every time you push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Deploy to Linode
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.LINODE_IP }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "dist/"
          TARGET: "/var/www/html"
          # -rlgoDzvc: standard sync flags
          # --delete: removes old build files from server
          ARGS: "-rlgoDzvc -i --delete"